### ISSUE TITLE
Add Task no longer works

### ISSUE THREAD

**Issue by IceGawd** [cse110-sp24-group21/cse110-sp24-group21#133]
Something changed the add tasks button and now it has the following error

```
Uncaught TypeError: tasks[date].forEach is not a function
    at tasks.js:171:17
    at Array.forEach (<anonymous>)
    at newTask (tasks.js:170:22)
    at HTMLButtonElement.<anonymous> (tasks.js:106:70)
```

**Comment by IceGawd** [comment]
It was an update to localstorage that caused this bug. Clearing localstorage does the trick
